version: "3.7"
services:
  app:
      build:
        args:
          user: goshva
          uid: 123
        context: ./
        dockerfile: dockerfile
      image: staffdev
      container_name: staffdev-app
      restart: unless-stopped
      working_dir: /var/www/
      depends_on: 
        - db
      volumes:
        - ./:/var/www
      networks:
        - staffdev-net

  db:
      image: mysql:5.7
      container_name: staffdev-db
      restart: unless-stopped
      ports:
        - 3333:3306
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      networks:
        - staffdev-net


  nginx:
      image: nginx:1.17-alpine
      container_name: staffdev-nginx
      restart: unless-stopped
      depends_on:
        - app
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
        - staffdev-net

networks:
  staffdev-net:
    driver: bridge